-- 코드를 입력하세요
WITH AA AS (
SELECT USER_ID, PRODUCT_ID, COUNT(USER_ID) 
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID)>1
)

SELECT USER_ID, PRODUCT_ID
FROM AA
ORDER BY USER_ID ASC, PRODUCT_ID DESC