-- 코드를 입력하세요
WITH SALES_LIST AS (
SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM ONLINE_SALE ONS

UNION ALL

SELECT NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM OFFLINE_SALE OFS
)

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM SALES_LIST
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY 1 ASC, 2 ASC, 3 ASC
