-- 코드를 작성해주세요
WITH AA AS (SELECT ID, CASE WHEN LENGTH IS NULL THEN 10
       ELSE LENGTH 
       END AS LENGTH_RE
FROM FISH_INFO
)

SELECT ROUND(SUM(LENGTH_RE) / COUNT(ID), 2) AS AVERAGE_LENGTH
FROM AA


