-- 코드를 입력하세요

SELECT RR.REST_ID, 
       REST_NAME, 
       FOOD_TYPE, 
       FAVORITES, 
       ADDRESS, 
       ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW RR
LEFT JOIN REST_INFO RI ON RR.REST_ID = RI.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY  6 DESC, 4 DESC