-- 코드를 입력하세요
WITH DIFFS AS (
SELECT *, TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS DIFF
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, ROUND(AVG(DIFF), 1) AS AVERAGE_DARATION
FROM DIFFS
GROUP BY CAR_ID
HAVING ROUND(AVG(DIFF), 1) >= 7
ORDER BY 2 DESC, 1 DESC