-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND(DAILY_FEE * (100 - COALESCE(P.DISCOUNT_RATE,0))/100 * (DATEDIFF(END_DATE, START_DATE) + 1),0) AS FEE
FROM (SELECT *, 
       CASE WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL END DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS H
JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON H.DURATION_TYPE = P.DURATION_TYPE
AND C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC

