-- 코드를 작성해주세요

SELECT SUM(SCORE) AS SCORE,
       EM.EMP_NO,
       EMP_NAME, 
       POSITION,
       EMAIL
FROM HR_EMPLOYEES EM
LEFT JOIN HR_DEPARTMENT DP ON EM.DEPT_ID = DP.DEPT_ID
LEFT JOIN HR_GRADE GD ON EM.EMP_NO = GD.EMP_NO
WHERE YEAR = '2022'
GROUP BY EM.EMP_NO
ORDER BY SCORE DESC
LIMIT 1