-- 코드를 입력하세요

   
SELECT FP.CATEGORY, MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
            FROM FOOD_PRODUCT
            GROUP BY CATEGORY) AS AA
ON FP.CATEGORY = AA.CATEGORY
AND FP.PRICE = AA.MAX_PRICE
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC