-- 코드를 작성해주세요

WITH AA AS (
SELECT FISH_TYPE, CASE WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH END AS LENGTH
        FROM FISH_INFO
)

SELECT COUNT(FISH_TYPE) AS FISH_COUNT, 
       MAX(LENGTH) AS MAX_LENGTH,
       FISH_TYPE
FROM AA
GROUP BY FISH_TYPE
HAVING SUM(LENGTH) / COUNT(FISH_TYPE) >= 33
ORDER BY FISH_TYPE